### ISSUE TITLE
Root paths with a param

### ISSUE THREAD

**Issue by chimon2000** [mrgnhnt96/go_router_paths#1]
I'm using your go_router_paths library, and I'd like to know how I would create a root-level path with a param injected somewhere in the path.

Something like: 

```
"/user/:id"
"/user/:id/pay"
"/user/:id/thank"
```

Where **pay** and **thank** are not child routes.

**Comment by mrgnhnt96** [comment]
Hey Ryan 👋 

This is currently not supported, though I'd like a little more context about this issue. Why would pay and thank _not_ be a nested routes? Is this due to how a project is already set up or how the project is being architected?

**Comment by chimon2000** [comment]
I actually rewrote these routes to be nested after thinking about it a bit.  Feel free to close this issue!
