### ISSUE TITLE
`.query` returns unexposed `Base`

### ISSUE THREAD

**Issue by andyhorn** [mrgnhnt96/go_router_paths#3]
If I build a path (`AppRoutes.root.users`) and add the `.query` modifier, it returns a `Base` instance instead of a `Path` or `Param`. This causes some of our extension methods (which are added to `Path` and `Param`) to be unavailable and we can't add extensions to `Base` because it isn't exposed from the package.

**Comment by mrgnhnt96** [comment]
Hey @andyhorn! 👋 

Thanks for creating an issue! I'm interested in knowing what your configuration is, could you give me some example code?

**Comment by andyhorn** [comment]
I spent some time writing an example before discovering I just didn't set it up properly 😆 

We have a parent route with `get`ters for its children and were using the `Path` type instead of the actual type of the route.

For example,

```dart
class RootRoute extends Path<RootRoute> {
  RootRoute(): super('/');

  Path get profile => ProfileRoute(); // the problem is here; it should return a ProfileRoute
}

class ProfileRoute extends Path<ProfileRoute> {
  ProfileRoute(): super('profile', parent: RootRoute());
}
```

Once we access that `profile` getter, it returned a `Path<Base<dynamic>>`; using `.query` on this object then returned just a `Base<dynamic>` which broke our extension.

I think you can close this as pure user error 👍

**Comment by mrgnhnt96** [comment]
Lol! All good, I'm glad that the package is serving you well! If you have any issues or questions, reach out! 💪
