### ISSUE TITLE
`GoRoute.path`, `go` or `push` with `.path` from a shared route/screen

### ISSUE THREAD

**Issue by FabianVarela** [mrgnhnt96/go_router_paths#4]
Hi @mrgnhnt96. Thanks for implementing this as a package.

I wonder if this issue is on the roadmap or if you didn't plan to address it. However, I have this problem with a `GoRoute` shared among screens. For example, the `detail screen` could be invoked from `screenA` or `screenB`, and the `detail screen` has more routes. In my case, I have a variable with this detail screen to avoid repeat code. 

```dart
// The detail screen

final _detailRoute = GoRoute(
  parentNavigatorKey: _rootNavigatorKey,
  path: 'detail/:id',
  pageBuilder: (_, state) {
    final id = int.parse(state.pathParameters['id']!);
    return FadeScreenPage<dynamic>(
      key: state.pageKey,
      child: DetailView(personId: id),
    );
  },
  routes: <GoRoute>[
       // There are more routes
  ],
);

final appRouter = GoRouter(
  initialLocation: AppRoutePath.screenA.goRoute,
  routes: <RouteBase>[
    StatefulShellRoute.indexedStack(
      branches: <StatefulShellBranch>[
        StatefulShellBranch(
          routes: <RouteBase>[
            GoRoute(
              path: AppRoutePath.screenA.goRoute,
              pageBuilder: (_, state) => ScreenPage<dynamic>(
                key: state.pageKey,
                child: const ScreenAView(),
              ),
              routes: <GoRoute>[_detailRoute],
            ),
          ],
        ),
        StatefulShellBranch(
          routes: <RouteBase>[
            GoRoute(
              path: AppRoutePath.screenB.goRoute,
              pageBuilder: (_, state) => ScreenPage<dynamic>(
                key: state.pageKey,
                child: const ScreenBView(),
              ),
              routes: <GoRoute>[_detailRoute],
          ],
        ),
      ],
      builder: (_, __, navigationShell) => BottomNavigationScaffold(
        navigationShell: navigationShell,
      ),
    ),
  ],
);
```

How can I detect the parent and know if I am on the correct route when setting the `GoRoute.path` value or even when I `go` or `push` from the `detail screen` to another screen from the `routes` array?

I hope you make me understand this problem.

**Comment by mrgnhnt96** [comment]
Hey @FabianVarela! 👋 

I think that this could be solved by creating an interface class to pass to the `_detailRoute` as an arg to dynamically set the routes.

Something like this?

```dart

// The detail screen

GoRoute _detailRoute(DetailPath path) => GoRoute(
      parentNavigatorKey: _rootNavigatorKey,
      path: path.goRoute,
      pageBuilder: (_, state) {
        final id = int.parse(state.pathParameters['id']!);
        return FadeScreenPage<dynamic>(
          key: state.pageKey,
          child: DetailView(personId: id),
        );
      },
      routes: const <GoRoute>[
        // There are more routes
      ],
    );

final appRouter = GoRouter(
  initialLocation: AppRoutePath.screenA.goRoute,
  routes: <RouteBase>[
    StatefulShellRoute.indexedStack(
      branches: <StatefulShellBranch>[
        StatefulShellBranch(
          routes: <RouteBase>[
            GoRoute(
              path: AppRoutePath.screenA.goRoute,
              pageBuilder: (_, state) => ScreenPage<dynamic>(
                key: state.pageKey,
                child: ScreenAView(),
              ),
              routes: <GoRoute>[_detailRoute(AppRoutePath.screenA.detail)],
            ),
          ],
        ),
        StatefulShellBranch(
          routes: <RouteBase>[
            GoRoute(
              path: AppRoutePath.screenB.goRoute,
              pageBuilder: (_, state) => ScreenPage<dynamic>(
                key: state.pageKey,
                child: ScreenBView(),
              ),
              routes: <GoRoute>[_detailRoute(AppRoutePath.screenA.detail)],
            ),
          ],
        ),
      ],
      builder: (_, __, navigationShell) => BottomNavigationScaffold(
        navigationShell: navigationShell,
      ),
    ),
  ],
);

class AppRoutePath {
  static ScreenA get screenA => ScreenA();
  static ScreenB get screenB => ScreenB();
}

class ScreenA extends Path {
  ScreenA() : super('screenA');

  DetailPath get detail => DetailPath();
}

class ScreenB extends Path {
  ScreenB() : super('screenB');

  DetailPath get detail => DetailPath();
}

class DetailPath extends Param {
  DetailPath() : super('detail', 'id');

  // Add more routes here
}
```

Let me know if this is what you're referring to and if it helps!

**Comment by FabianVarela** [comment]
Hi, @mrgnhnt96, thanks for your reply. Yeah, this part of this `GoRouter` implementation works okay.

The topic is when I make `go` or `push` from the `DetailView`. For example, I'm in the `DetailView` and have more routes inside it, and I need to know if I'm in `ScreenA` or `ScreenB`. In this case, what can I pass `AppRoutePath. screenA.detail.otherRoute` or `AppRoutePath.screenB.detail.otherRoute`?

I hope you make me understand this last problem.

**Comment by mrgnhnt96** [comment]
Oh I gotcha, hmm. I would approach this using `ModalRoute.of(context).settings.name`. You could check to see which screen you're in and then navigate based on that. You can read more about it [here](https://stackoverflow.com/questions/46483949/how-to-get-current-route-path-in-flutter)

**Comment by FabianVarela** [comment]
I was reviewing to get the path location from `GoRouterState.of(context).uri`. However, there exists an open [issue](https://github.com/flutter/flutter/issues/129833), and I implemented the solution given in this issue.

Anyway, I get the previous path, but in this case, I have to validate what is the string route to get the `Path` or `Param` class. For example:

```dart
Param getPreviousPath() {
  final previousLocation = GoRouterState.of(context).uri.path;
  if (prevousLocation.contains(AppRoutePath.screenA.goRoute)) {
     return AppRoutePath.screenA.detail;
  }
}
```

What do you think about this solution?

**Comment by mrgnhnt96** [comment]
I think that that could work for you! Were you able to get it working with that?

**Comment by FabianVarela** [comment]
Sure, I have to take more steps, but that part is outside your hands, and this is not the package's target. I appreciate your support. I am going to close the issue
